<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrograAvanzada.Viernes.MyLibraryDbModel\PrograAvanzada.Viernes.MyLibraryDbModel.csproj" />
    <ProjectReference Include="..\PrograAvanzada.Viernes.MyLibraryRepository\PrograAvanzada.Viernes.MyLibraryRepository.csproj" />
  </ItemGroup>

</Project>
